use_frameworks!

platform :ios, '10.0'

target 'SwiftCore_Example' do
  pod 'SwiftCore', :path => '../'
  
#  pod 'MLeaksFinder', '~> 1.1.0'
#  pod 'LookinServer'

  target 'SwiftCore_Tests' do
    inherit! :search_paths

    
  end
end
